/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import java.util.Collections;
import java.util.List;

public class Main {
    public static void main(String... args) {

        List<Integer> list1 = new DIYArrayList<>();
        List<Integer> list2 = new DIYArrayList<>();
        // Заполнение списка list1
        Collections.addAll(list1, 1, 5, 20, 10, 2, 6, 19, 8, 9, 4, 11, 12, 13, 14, 15, 16, 17, 18, 7, 3);
        printList(list1, "Cписок: ");
        // Сортировка списка list1 по возрастанию и убыванию
        Collections.sort(list1);
        printList(list1, "Отсортированный по возрастанию список: ");
        Collections.sort(list1, Collections.reverseOrder());
        printList(list1, "Отсортированный по убыванию список: ");
        // Заполнение списка list2 нулями
        for (int i = 0; i < 20; i++) {
            list2.add(0);
        }
        // Копируем список list1 в list2
        Collections.copy(list2, list1);
        printList(list2, "Копия списка: ");

    }

    private static void printList(List<? extends Number> list, String msg) {
        System.out.print(msg);
        list.forEach(numb -> System.out.printf("%s ", numb.toString()));
        System.out.println();
    }
}
