/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import java.util.Arrays;
import java.util.Collection;

public class Main {
    public static void main(String... args) throws Exception {
        Class<?> clazz = Class.forName("ru.otus.BirthDayTest");
        // данные для тестирования
        Collection testData = Arrays.asList(new int[][]{
                {1993, 2, 3},
                {2005, 4, 6}
        });
        // запуск тестирования
        RunTests.runTestsBirthDay(clazz, testData);
    }
}
